### ISSUE TITLE
uninitialized constant Objectify::Rails::ObjectifyController

### ISSUE THREAD

**Issue by caironoleto** [FetLife/objectify#11]
Hi! I started with objectify and after config the app and add the first resource

```ruby
  objectify.resources :articles
```

I get the following error:

`uninitialized constant Objectify::Rails::ObjectifyController`

But, after load `Objectify::Rails::ControllerHelpers` in console, rails recognize `Objectify::Rails::ObjectifyController`, see:

```irb
Loading development environment (Rails 3.2.6)
1.9.3p194 :001 > Objectify::Rails::ObjectifyController
NameError: uninitialized constant Objectify::Rails::ObjectifyController
	from (irb):1
	from /Users/caironoleto/.rvm/gems/ruby-1.9.3-p194@obj/gems/railties-3.2.6/lib/rails/commands/console.rb:47:in `start'
	from /Users/caironoleto/.rvm/gems/ruby-1.9.3-p194@obj/gems/railties-3.2.6/lib/rails/commands/console.rb:8:in `start'
	from /Users/caironoleto/.rvm/gems/ruby-1.9.3-p194@obj/gems/railties-3.2.6/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
1.9.3p194 :002 > Objectify::Rails::ControllerHelpers
 => Objectify::Rails::ControllerHelpers 
1.9.3p194 :003 > Objectify::Rails::ObjectifyController
 => Objectify::Rails::ObjectifyController 
```

**Comment by lauradoox** [comment]
Is this still an issue we need to resolve or can we close this?
